name: Terraform Rollback Infrastructure

on:
  workflow_dispatch: # Allows manual trigger
    inputs:
      reason:
        description: "Reason for rollback"
        required: true
        default: "Manual rollback requested"
      confirm:
        description: "Type 'yes' to confirm rollback"
        required: true
        default: "no"

jobs:
  terraform-rollback:
    name: Rollback Infrastructure
    runs-on: ubuntu-latest

    env:
      AWS_REGION: "us-east-1"

    steps:
    # 1. Checkout Code
    - name: Checkout Code
      uses: actions/checkout@v3

    # 2. Setup AWS Credentials
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: ${{ env.AWS_REGION }}

    # 3. Setup Terraform
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.0


    # 4. Fetch the Latest State File
    - name: Pull Current State
      run: aws s3 cp s3://bckt-neeraj/prod/terraform.tfstate ./terraform.tfstate

    # Generate Human-Readable State Before Rollback
    - name: Show Current State
      run: terraform show ./terraform.tfstate > pre_rollback_state.txt


    - name: Initialize Terraform
      run: terraform init
      
    - name: Apply Previous State
      run: terraform apply -auto-approve

      
    # Show Human-Readable State After Rollback
    - name: Show Post-Rollback State
      run: terraform show > post_rollback_state.txt
