name: Terraform CI/CD Pipeline with Rollback

on:
  push:
    branches:
      - main32
  workflow_dispatch: # Allows manual triggers

jobs:
  terraform:
    name: Terraform Deployment and Rollback
    runs-on: ubuntu-latest

    env:
      AWS_REGION: "us-east-1" 

    steps:
    # 1. Checkout Code
    - name: Checkout Code
      uses: actions/checkout@v3

    # 2. Setup Terraform
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.0

    # 3. Configure AWS Credentials
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    # 4. Initialize Terraform
    - name: Terraform Init
      run: terraform init

    # 5. Terraform Plan
    - name: Terraform Plan
      id: plan
      run: terraform plan -out=tfplan

    # 6. Apply Terraform Changes
    - name: Terraform Apply
      if: success()
      run: terraform apply -auto-approve tfplan

    # 7. Rollback on Failure
    - name: Terraform Rollback
      if: failure()
      run: |
        echo "Rollback triggered due to failure."
        echo "Fetching the previous state file..."
        aws s3 cp s3://bckt-neeraj/prod/terraform.tfstate ./terraform.tfstate
        echo "Reverting to the previous state..."
        terraform apply -auto-approve ./terraform.tfstate
